# Generated by Django 5.2.8 on 2025-12-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('scrape_products', 'Scrape Products')], max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-last_updated']},
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL of the product image', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, help_text="Product rating (e.g., 'Five', 'Four')", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original source URL of the product', max_length=500, null=True),
        ),
    ]
