# Generated by Django 5.2.8 on 2025-12-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_automationjob_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time product was synced from source', null=True),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='job_type',
            field=models.CharField(choices=[('scrape_products', 'scrape_products')], max_length=50),
        ),
        migrations.AlterField(
            model_name='automationjob',
            name='status',
            field=models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, help_text='Product rating as integer (0-5)', null=True),
        ),
    ]
